version: "3"
services:
  web:
    build: .
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    links:
      - db
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  celery:
    build: .
    command: celery worker -A happinesspackets -l info
    links:
      - db
      - redis
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: example
